spring:
  application:
    name: crm-task

  datasource:
    url: jdbc:postgresql://localhost:5432/crm_db
    username: postgres
    password: mysecretpassword
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  liquibase:
    change-log: db/changelog-master.yaml
    enabled: true

logging:
  level:
    liquibase: DEBUG
    org.springframework.security: trace

jwt:
  secret: 9rvuHvQY8fPmkQoVdPo7OQg4NYrmcJkjsYYBZj5gL0A=
  access-token-expiration: 900000
